trigger url on success

diff --git a/.github/workflows/release-create-pr.yml b/.github/workflows/release-create-pr.yml
--- a/.github/workflows/release-create-pr.yml
+++ b/.github/workflows/release-create-pr.yml
@@ -7,6 +7,10 @@ on:
         description: 'The branch, tag, or commit to create this release PR from.'
         required: true
         default: 'master'
+      resumeUrl:
+        description: 'URL to call after the build is successful'
+        required: false
+        type: string
 
       release-type:
         description: 'A SemVer release type.'
@@ -73,3 +77,17 @@ jobs:
           labels: release,release:${{ github.event.inputs.release-type }}
           title: ':rocket: Release ${{ env.NEXT_RELEASE }}'
           body-path: 'CHANGELOG-${{ env.NEXT_RELEASE }}.md'
+  call-success-url:
+    name: Call Success URL
+    needs: [create-release-pr]
+    runs-on: ubuntu-latest
+    if: needs.create-release-pr.result == 'success' || needs.create-release-pr.result == 'skipped'
+    steps:
+      - name: Call Success URL
+        env:
+          SUCCESS_URL: ${{ github.event.inputs.resumeUrl }}
+        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.resumeUrl != '' }}
+        run: |
+          echo "Calling success URL: ${{ env.SUCCESS_URL }}"
+          curl -v "${{ env.SUCCESS_URL }}" || echo "Failed to call success URL"
+        shell: bash
